name: Ping Spousetaker

on:
  workflow_dispatch: # Allows manual trigger
  schedule:
    - cron: "*/15 * * * *" # Runs every 15 minutes (for initial trigger)

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run Ping Script
      run: |
        python ping_script.py

    - name: Trigger Next Workflow Run
      if: always() # Always trigger the next workflow, even if the script errors
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/ping.yml/dispatches \
          -d '{"ref":"main"}'
